apiVersion: v1
kind: ReplicationController
metadata:
  name: bnw-rc
spec:
  replicas: 2
  selector:
      app: brave-new-world  #pod
  template:
    metadata:
      name: brave-new-world
      labels:
        app: brave-new-world
    spec:
      containers:
      - name: hallowelt
        image: lionasis/hallowelt
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
