apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hallowelt
spec:
  rules:
  - host: hallowelt.info
    http:
      paths:
      - path: /
        backend:
          service:
            name: hallowelt-nodeport
            port:
              number: 80
